### ISSUE TITLE
Can I use @types/dagre-d3  as the type definitions of dagre-d3v4 ? 

### ISSUE THREAD

**Issue by ninesunqian** [smbolton/dagre-d3v4#4]
Hello，
Can I use @types/dagre-d3  as the type definitions of dagre-d3v4 ? 
https://www.npmjs.com/package/@types/dagre-d3

**Comment by theabolton** [comment]
The only thing that changed in the dagre-d3v4 0.5.x API, from dagre-d3, is edge path line interpolation, which isn't covered by the @types/dagre-d3 package. So it looks like it would work. But since the type definitions are based on a different code base than the dagre-d3v4 source, I couldn't guarantee it, now or for future versions.

**Comment by ninesunqian** [comment]
I have tested it.  @types/dagre-d3 can't  be adapted  dagre-d3v4, becase the type definition of "selecton" are different in d3v3 and d3v4.  Currently I use  @types/dagre-d3,  with looking forward to  @types/dagre-d3v4.

Thank you!
